#%RAML 1.0 Library
types:
  GetTicketDetailsRequest:  !include /exchange_module/types/get-ticket-details-input-data-type.raml
  GetTicketDetailsResponse: !include  /exchange_module/types/get-ticket-details-output-data-type.raml
  SuccessResponse:          !include  /exchange_module/types/success-response.raml
